# Generated by Django 3.1.1 on 2020-12-20 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pagarme', '0004_pagarme_item_config_available_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarmeformconfig',
            name='boleto_discount_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pagarmeformconfig',
            name='credit_card_discount_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
